/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.insa.pons.main;

import fr.insa.pons.chronometre.ChronometreGUI;
import fr.insa.pons.endurance.EnduranceGUI;

/**
 *
 * @author hugop
 */
public class MenuPrincipal extends javax.swing.JFrame {
private ChronometreGUI ChronoFen ;
private EnduranceGUI EnduranceFen ;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jButtonChrono = new javax.swing.JButton();
        jButtonStatsChrono = new javax.swing.JButton();
        jButtonEndurance = new javax.swing.JButton();
        jButtonStatsEndu = new javax.swing.JButton();
        jButtonTraining = new javax.swing.JButton();
        jButtonStatsTraining = new javax.swing.JButton();
        jButtonLecons = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanelMenu.setBackground(new java.awt.Color(240, 148, 63));
        jPanelMenu.setLayout(new java.awt.GridLayout(4, 2, 10, 25));

        jButtonChrono.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButtonChrono.setForeground(new java.awt.Color(255, 0, 0));
        jButtonChrono.setText("Chronomètre");
        jButtonChrono.setToolTipText("");
        jButtonChrono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonChrono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChronoActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonChrono);

        jButtonStatsChrono.setText("Statistiques");
        jPanelMenu.add(jButtonStatsChrono);

        jButtonEndurance.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButtonEndurance.setForeground(new java.awt.Color(255, 0, 0));
        jButtonEndurance.setText("Endurance");
        jButtonEndurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnduranceActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButtonEndurance);

        jButtonStatsEndu.setText("Statistiques");
        jPanelMenu.add(jButtonStatsEndu);

        jButtonTraining.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButtonTraining.setForeground(new java.awt.Color(255, 0, 0));
        jButtonTraining.setText("Training");
        jPanelMenu.add(jButtonTraining);

        jButtonStatsTraining.setText("Statistiques");
        jPanelMenu.add(jButtonStatsTraining);

        jButtonLecons.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButtonLecons.setForeground(new java.awt.Color(255, 0, 0));
        jButtonLecons.setText("Leçons");
        jPanelMenu.add(jButtonLecons);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChronoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChronoActionPerformed
ChronoFen = new ChronometreGUI();
ChronoFen.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChronoActionPerformed

    private void jButtonEnduranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnduranceActionPerformed
EnduranceFen = new EnduranceGUI();
EnduranceFen.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnduranceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChrono;
    private javax.swing.JButton jButtonEndurance;
    private javax.swing.JButton jButtonLecons;
    private javax.swing.JButton jButtonStatsChrono;
    private javax.swing.JButton jButtonStatsEndu;
    private javax.swing.JButton jButtonStatsTraining;
    private javax.swing.JButton jButtonTraining;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
