/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.insa.pons.endurance;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Timer;

/**
 *
 * @author hugop
 */
public class EnduranceMode extends javax.swing.JFrame {

    private ArrayList<Integer> UserAnswers;
    private ArrayList<Integer> RealAnswers;
    private int countdown, minDigits, maxDigits,unDigit=0, Nombre1, Nombre2 ;
    private Timer Countdown ;
    private JPanelFin FinSansTimer ;

    /**
     * Creates new form EnduranceMode
     */
    public EnduranceMode(int minDigits, int maxDigits) {
        UserAnswers = new ArrayList<>();
        RealAnswers = new ArrayList<>();
        this.minDigits = minDigits;
        this.maxDigits = maxDigits;
        initComponents();
        Nombre1 = RandomNumber(minDigits, maxDigits);
        Nombre2 = RandomNumber(minDigits, maxDigits);
        jTextAreaCalculs.setText(Nombre1 + " * " + Nombre2);
        RealAnswers.add(Nombre1 * Nombre2);
        jButtonFin.setEnabled(true);
    }
    public EnduranceMode(int unDigit,int minDigits, int maxDigits,boolean useless){
     UserAnswers = new ArrayList<>();
     RealAnswers = new ArrayList<>();
     this.unDigit = unDigit ;
       this.minDigits = minDigits;
        this.maxDigits = maxDigits;
     initComponents();
     Nombre1 = unDigit ;
     Nombre2 = RandomNumber(minDigits,maxDigits) ;
     jTextAreaCalculs.setText(Nombre1 + " * " + Nombre2);
     RealAnswers.add(Nombre1 * Nombre2);
        jButtonFin.setEnabled(true);
    }

    public EnduranceMode(int mode, int minDigits, int maxDigits) {
        ActionListener compte_a_rebours ;
        UserAnswers = new ArrayList<>();
        RealAnswers = new ArrayList<>();
        this.minDigits = minDigits;
        this.maxDigits = maxDigits;
        initComponents();
        countdown = SelectionMode(mode);
        Nombre1 = RandomNumber(minDigits, maxDigits);
        Nombre2 = RandomNumber(minDigits, maxDigits);
        jTextAreaCalculs.setText(Nombre1 + " * " + Nombre2);
        RealAnswers.add(Nombre1 * Nombre2);
        Countdown CompteARebours = new Countdown(countdown);
        compte_a_rebours = new ActionListener(){
        public void actionPerformed(ActionEvent e){
            if(CompteARebours.getSecondes() == 0){
                CompteARebours.setMinutes(CompteARebours.getMinutes()-1);
                CompteARebours.setSecondes(59);
            } else {
                CompteARebours.setSecondes(CompteARebours.getSecondes()-1);
            }
            jLabelCountdown.setText(CompteARebours.getMinutes()+ " : "+CompteARebours.getSecondes());
        }
        };
        Countdown = new Timer(1000,compte_a_rebours);
        Countdown.start();
    }
        public EnduranceMode(int mode,int unDigit, int minDigits, int maxDigits) {
        ActionListener compte_a_rebours ;
        UserAnswers = new ArrayList<>();
        RealAnswers = new ArrayList<>();
        this.minDigits = minDigits;
        this.maxDigits = maxDigits;
        this.unDigit = unDigit ;
        initComponents();
        countdown = SelectionMode(mode);
        Nombre1 = unDigit;
        Nombre2 = RandomNumber(minDigits, maxDigits);
        jTextAreaCalculs.setText(Nombre1 + " * " + Nombre2);
        RealAnswers.add(Nombre1 * Nombre2);
        Countdown CompteARebours = new Countdown(countdown);
        compte_a_rebours = new ActionListener(){
        public void actionPerformed(ActionEvent e){
            if(CompteARebours.getSecondes() == 0){
                CompteARebours.setMinutes(CompteARebours.getMinutes()-1);
                CompteARebours.setSecondes(59);
            } else {
                CompteARebours.setSecondes(CompteARebours.getSecondes()-1);
            }
            jLabelCountdown.setText(CompteARebours.getMinutes()+ " : "+CompteARebours.getSecondes());
        }
        };
        Countdown = new Timer(1000,compte_a_rebours);
        Countdown.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCalculs = new javax.swing.JTextArea();
        jLabelCountdown = new javax.swing.JLabel();
        jLabelEssais = new javax.swing.JLabel();
        jTextFieldAnswers = new javax.swing.JTextField();
        jButtonFin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaCalculs.setEditable(false);
        jTextAreaCalculs.setColumns(20);
        jTextAreaCalculs.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextAreaCalculs.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCalculs);

        jTextFieldAnswers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnswersActionPerformed(evt);
            }
        });

        jButtonFin.setText("FIN");
        jButtonFin.setEnabled(false);
        jButtonFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabelCountdown, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(jLabelEssais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jTextFieldAnswers, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCountdown, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEssais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldAnswers, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonFin)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAnswersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnswersActionPerformed
        
       
        UserAnswers.add(Integer.parseInt(jTextFieldAnswers.getText().trim()));
        jTextFieldAnswers.setText("");
        if(unDigit==0){
        Nombre1 = RandomNumber(minDigits, maxDigits);
        Nombre2 = RandomNumber(minDigits, maxDigits);
        jTextAreaCalculs.setText(Nombre1 + " * " + Nombre2);
        RealAnswers.add(Nombre1 * Nombre2);
        jLabelEssais.setText(Integer.toString(UserAnswers.size()));
        } else {
         Nombre1 = unDigit ;
         Nombre2 = RandomNumber(minDigits, maxDigits);
        jTextAreaCalculs.setText(Nombre1 + " * " + Nombre2);
        RealAnswers.add(Nombre1 * Nombre2);
        jLabelEssais.setText(Integer.toString(UserAnswers.size()));
        }
    }//GEN-LAST:event_jTextFieldAnswersActionPerformed

    private void jButtonFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinActionPerformed
FinSansTimer = new JPanelFin();
int ReponsesJustes = ReponsesCorrectes(UserAnswers,RealAnswers) ;
FinSansTimer.getjTextArea1().setText("") ;

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnduranceMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnduranceMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnduranceMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnduranceMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EnduranceMode().setVisible(true);
            }
        });
    }

    private static int SelectionMode(int mode) {
        int ans = 0;
        switch (mode) {
            case 0: {
                ans = 1;
            }
            break;
            case 1: {
                ans = 2;
            }
            break;
            case 2: {
                ans = 5;
            }
            break;
            case 3: {
                ans = 10;
            }
            break;
        }
        return (ans);
    }

    private static int RandomNumber(int min, int max) {
        int ans = -1;
        int digits;
        System.out.println("MIN =" + min + " MAX=" + max);

        if (min == max) {
            digits = min;
        } else {
            digits = (int) ((Math.random() * (max - min)) + min);
        }
        while ((ans < Math.pow(10, min)) || (ans > Math.pow(10, max))) {
            ans = (int) (Math.random() * Math.pow(10, digits));
            System.out.println("ligne 220" + ans);
        }
        System.out.println("REPONSE =" + ans);
        return (ans);
    }
    public static int ReponsesCorrectes(ArrayList<Integer>ReponsesDonnees,ArrayList<Integer>ReponsesVraies){
        int nb = 0 ;
    for(int i = 0 ; i<ReponsesDonnees.size();i++){
       if(ReponsesDonnees.get(i)==ReponsesVraies.get(i)){
           nb = nb + 1 ;
       } 
    }
       return nb ; 
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFin;
    private javax.swing.JLabel jLabelCountdown;
    private javax.swing.JLabel jLabelEssais;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCalculs;
    private javax.swing.JTextField jTextFieldAnswers;
    // End of variables declaration//GEN-END:variables
}
